### ISSUE TITLE
worker scaling off by one

### ISSUE THREAD

**Issue by anyaelena** [NREL/OpenStudio-aws-gem#22]
On a 356 CPU set up, we're seeing the following reservations:

11 web
6 db
1 queue
1 rserve
1 web-background

This leave 336 CPUs available, but workers are being scaled to 337.

**Comment by nllong** [comment]
Yes I agree. @rHorsey  can you commit to fixing this?

**Comment by anyaelena** [comment]
@nllong agreed to take this one
