### ISSUE TITLE
develop3 branch

### ISSUE THREAD

**Issue by anyaelena** [NREL/OpenStudio-aws-gem#26]
1. go/no go on move to Kubernetes
2. finish K8 or close VPC PR

**Comment by anyaelena** [comment]
@nllong @brianlball @rHorsey this is happening

**Comment by tijcolem** [comment]
We are moving forward with k8s/helm with OpenStudio-server. Any new issue related to that can be opened at: https://github.com/NREL/openstudio-server-helm

Closing this issue.
