### ISSUE TITLE
Check if server instance has enough CPUs

### ISSUE THREAD

**Issue by brianlball** [NREL/OpenStudio-aws-gem#29]
A server can be started that does not have enough CPUs to support the docker swarm.  This causes the entire cluster to not startup, but the user is still being charged for the instances.  create a check for the number of CPUs that will be needed according to the cluster configuration before starting the cluster

**Comment by tijcolem** [comment]
@brianlball I'm closing out in favor of the k8s/helm at https://github.com/NREL/OpenStudio-server-helm
